pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('hello-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('hello-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('hello-app') {
                    sh 'java -cp target/hello-app-1.0-SNAPSHOT.jar com.devops.App'
                }
            }
        }
    }
}
