pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('hello-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('hello-app') {
                    sh 'mvn test'
                }
            }
        }

    }
}
